services:
  app:
    build: 
      context: .
      dockerfile: app/Dockerfile
    networks:
      - backnet
    depends_on:
      - db
    command: php -S 0.0.0.0:3000 -t .
    ports: 
     - "3000:3000" 
    secrets:
      - db_password
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
  db:
    image: mysql:8
    restart: always
    secrets:
      - db_root_password
      - db_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    expose:
      - ${MYSQL_PORT}
      - 33060
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backnet

volumes:
  db-data:

secrets:
  db_root_password:
    file: db/root_password.txt
  db_password:
    file: db/user_password.txt
networks:
  backnet: