  services:
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      networks:
        - backend
      depends_on:
        - db
    app:
      volumes:
      - ${PWD}/app/code:/usr/src/app
      