  services:
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      networks:
        - backend
      depends_on:
        - db
    app:
        command: php -e -S 0.0.0.0:3000 -t .